version: "3.7"

services:

  php-env:
    build: .

    volumes:
      - ./prestigetravels:/var/www/html 

    ports:
      - 80:80

    networks:
      - prestigetravels
      
    depends_on:
      db:
        condition: service_healthy

  db: 
    image: mysql:latest
    restart: always
    volumes:
      - ./prestigetravels/DB:/var/lib/mysql
      - ./db-scripts:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: user
      MYSQL_PASSWORD: pass
      MYSQL_DATABASE: prestigetravels
    networks:
      - prestigetravels
    healthcheck:
      test: ["CMD-SHELL", "[ -n \"$(ls -A /var/lib/mysql)\" ]"]
      interval: 10s
      timeout: 10s
      retries: 4

  phpmyadmin:
    image: phpmyadmin:latest
    restart: always
    ports:
      - 8080:80
    environment:
      PMA_HOST: db
      PMA_USER: root
      PMA_PASSWORD: root
    networks:
      - prestigetravels
    depends_on:
      db:
        condition: service_healthy

networks:
  prestigetravels:
    driver: bridge
